### ISSUE TITLE
At doorkeeper v3.0.0, fails when render unauthorized with wrong number of arguments

### ISSUE THREAD

**Issue by kenchan0130** [taiki45/garage-doorkeeper#1]
Hi,

I have a recent installation of doorkeeper, 3.0.0.

When render unauthorized,  a error that is `wrong number of arguments (1 for 0)` occurs at `doorkeeper_unauthorized_render_options(error: error)` line of [`Doorkeeper::Rails::Helpers#doorkeeper_unauthorized_render_options`](https://github.com/doorkeeper-gem/doorkeeper/blob/master/lib/doorkeeper/rails/helpers.rb#L14)

Perhaps, this is because from version 3.0.0 of the impact of the changed method arguments.

The following is part of the stack trace.

```
ArgumentError - wrong number of arguments (1 for 0):
  doorkeeper (3.0.0) lib/doorkeeper/rails/helpers.rb:53:in `doorkeeper_render_options'
  doorkeeper (3.0.0) lib/doorkeeper/rails/helpers.rb:33:in `doorkeeper_render_error_with'
  doorkeeper (3.0.0) lib/doorkeeper/rails/helpers.rb:29:in `doorkeeper_render_error'
  doorkeeper (3.0.0) lib/doorkeeper/rails/helpers.rb:10:in `doorkeeper_authorize!'
  activesupport (4.2.3) lib/active_support/callbacks.rb:430:in `block in make_lambda'
  activesupport (4.2.3) lib/active_support/callbacks.rb:162:in `block in halting'
  activesupport (4.2.3) lib/active_support/callbacks.rb:502:in `block in call'
  activesupport (4.2.3) lib/active_support/callbacks.rb:502:in `call'
  activesupport (4.2.3) lib/active_support/callbacks.rb:496:in `block (2 levels) in around'
  activesupport (4.2.3) lib/active_support/callbacks.rb:311:in `block (2 levels) in halting'
   () /Myapp/vendor/bundle/ruby/2.2.0/bundler/gems/garage-ff712b31d3ff/lib/garage/controller_helper.rb:89:in `notify_request_stats'
```

**Comment by taiki45** [comment]
@kenchan0130 resolved by https://github.com/cookpad/garage/pull/34 ?

**Comment by kenchan0130** [comment]
@taiki45 
yap.  Thanks for reminding me.
